### ISSUE TITLE
Benutzerdefinierte Felder in den Solr-Index aufnehmen

### ISSUE THREAD

**Issue by hermann77** [OPUS4/userdoc#73]
Hallo,
wenn es möglich ist, dass die neue/benutzerdefinierte (Enrichment) Felder auch durch Solr indexiert werden, könntet ihr bitte dies in die Doku aufnehmen?

Meine Experimente mit
OPUS4/application/configs/solr/solr.xslt
und 
schema.xml unter SOLR

Scheiterten bisher.

Danke euch im Voraus!

**Comment by j3nsch** [comment]
Hallo,

die Enrichments sind noch nicht mit in die Suche aufgenommen. Das ist für OPUS 4.7 geplant und Teil einer größeren Erweiterung der Suchfunktionen. 

Die Dokumentation hängt immer ein wenig hinterher, weil nicht genügend Kapazitäten vorhanden sind, aber die Suche nach Enrichments wird sehr prominent hervorgehoben werden.

Viele Grüße
OPUS 4 Team

**Comment by j3nsch** [comment]
Seit 4.7 kann man ja auch Enrichments indexieren und als Facetten konfigurieren. Haben wir das schon in die Dokumentation aufgenommen? Ist diese Aufgabe vielleicht schon erledigt oder muss noch was ergänzt werden?

**Comment by stconradr** [comment]
Dieses Feature ist schon in der aktuellen Doku (gh-pages) enthalten unter dem Punkt 4.7. :-)
Ich werde noch ein paar Schreibfehler korrigieren.
