### ISSUE TITLE
Hinweise zu XMetaDissPlus in Dokumentation aufnehmen

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/userdoc#92]
Die Verwendung von Element `<pc:personEnteredUnderGivenName>' in OPUS 4 für XMetaDissPlus dokumentieren. 

Ich denke wir sollten eine neue Seite für XMetaDissPlus in der Dokumentation anlegen. Die Datei `xmetadissplus.md` könnte im Ordner `export` angelegt werden. Dort könnten im Laufe der Zeit weiter Informationen zum Format gesammelt werden. Ich denke das macht langfristig mehr Sinn als, eine Sektion in `export/oaiexport.md`, aber auch das ist eine Möglichkeit.

**Comment by j3nsch** [comment]
Ich habe das Ticket jetzt erst einmal zugewiesen, aber es kann auch gerne an jemand anderen weitergereicht werden.

**Comment by stconradr** [comment]
Habe unter export/oaiexport.md die Formate der OAI-Schnittstelle eingetragen und dort einige Hiweise zu XMetaDissPlus platziert, u.a. den Hinweis zum  Element `pc:personEnteredUnderGivenName'. Ebenfalls findet sich ein Hinweis dazu bei den Personenfeldern unter reference/fields. Signe hat nochmal alles reviewed.
