### ISSUE TITLE
DOI-Generierung und Registrierung

### ISSUE THREAD

**Issue by NelliTaller** [OPUS4/userdoc#98]
Auf der Seite https://www.opus-repository.org/userdoc/integration/doi.html steht folgendes am 04.03.2022 geschrieben: "DOIs können von akademischen Institutionen, wie Universitäten und Hochschulen, mit dem Fokus auf Forschungsdaten beim DataCite-Konsortium kostenfrei registriert werden. In Deutschland ist hierfür die Technische Informationsbibliothek (TIB) in Hannover als DataCite-Konsortialmitglied zuständig. Vor der Aktivierung der DOI-Registrierung in OPUS muss ein entsprechender Vertrag mit der TIB geschlossen werden."
Diese Informationen sind nicht (mehr) korrekt. Im April 2020 hat DataCite sein Kosten- und Mitgliedsmodell geändert. Der obige Text könnte zum Beispiel wie folgt ersetzt werden: 
"DOIs können von akademischen Institutionen, wie Universitäten und Hochschulen über eine direkte DataCite Mitgliedschaft (https://datacite.org/become.html) oder über ein DataCite-DOI-Konsortium registriert werden. In Deutschland gibt es zur Zeit (Stand März 2022) fünf DataCite-DOI-Konsortien (alphabetische Reihenfolge): 
- DARA Konsortium (https://www.da-ra.de/get-a-doi#become-a-user)
- DOI-Konsortium NRW (https://service-wiki.hbz-nrw.de/display/DOI/FAQ+zum+DOI-Konsortium)
- SUB Göttingen Konsortium (https://www.eresearch.uni-goettingen.de/de/knowledge-base/howto/getting-an-identifier/)
- TIB DOI Konsortium (https://projects.tib.eu/pid-service/tib-doi-konsortium/mitglied-werden/)
- ZB MED DOI-Konsortium (https://www.publisso.de/wir-fuer-sie/doi-service/)

Eine aktuelle Auflistung und Beschreibung der deutschen DOI-Konsortien finden Sie hier: https://projects.tib.eu/pid-service/tib-doi-konsortium/faqs/
Vor der Aktivierung der DOI-Registrierung in OPUS muss ein entsprechender Vertrag mit DataCite oder einem Konsortium geschlossen, ein Repository Konto in Fabrica eingerichtet und ein Präfix zugewiesen werden. Informationen zu Fabrica finden Sie im DataCite Fabrica Handbuch (https://wiki.tib.eu/confluence/display/pid/DataCite+Fabrica+Handbuch+Startseite)."

**Comment by stconradr** [comment]
Danke für die ausführlichen Hinweise. Das werden wir anpassen.
